import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import MainView from "../layouts/MainView";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Save your memory as a NFT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainView>
        <div className="flex h-full min-h-screen w-full flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Save your memory as a{" "}
            <span className="text-[hsl(280,100%,70%)]">NFT</span>
          </h1>
          <div className="flex items-center">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/create"
            >
              <h3 className="text-2xl font-bold">Start Now</h3>
              <div className="text-lg">
                Share your image as a ERC-1155 NFT and keep it forever
              </div>
            </Link>
          </div>
        </div>
      </MainView>
    </>
  );
};

export default Home;
